config/routes.rb
Rails.application.routes.draw do
  
  root to: "shifts#index"
  devise_for :users
  resources :users, only: [:index, :new, :destroy, :edit]
  resources :shifts, only: [:index, :create, :show, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
require 'date'

private def date_valid?(str)
  !!Date.parse(str)
        rescue StandardError
          false
end

class Shift < ApplicationRecord
  belongs_to :user
  validates :work_day, timeliness: { on_or_after: Time.now.since(2.weeks).monday }
  validates :work_day, uniqueness: { scope: :user_id }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_is_after_start_time
  validate :break_end_is_after_break_start
  validate :end_time_is_after_break_end
  validate :break_start_is_after_start_time

  def end_time_is_after_start_time
    return if end_time.blank? || start_time.blank?
    errors.add(:end_time, 'は出勤時間より後にしてください') if  end_time < start_time
  end
  def break_end_is_after_break_start
    return if break_end.blank? || break_start.blank?
    errors.add(:break_end, 'は休憩開始時間より後にしてください') if break_end < break_start
  end
  def end_time_is_after_break_end
    return if end_time.blank? || break_end.blank?
    errors.add(:end_time, 'は休憩終了時間より後にしてください') if end_time < break_end
  end
  def break_start_is_after_start_time
    return if break_start.blank? || start_time.blank?
    errors.add(:break_start, 'は出勤時間より後にしてください') if break_start < start_time
  end
end

app/models/shifts_collection.rb
# ユーザーのコレクションモデル
class ShiftsCollection
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations
  SHIFT_NUM = 7 # 同時にユーザーを作成する数
  attr_accessor :collection

  # 初期化メソッド
  def initialize(attributes = [])
    self.collection = if attributes.present?
                        attributes.map do |value|
                          Shift.new(
                            work_day: value['work_day'],
                            start_time: value['start_time'],
                            end_time: value['end_time'],
                            break_start: value['break_start'],
                            break_end: value['break_end']
                          )
                        end
                      else
                        SHIFT_NUM.times.map { Shift.new }
                      end
  end

  # レコードが存在するか確認するメソッド
  def persisted?
    false
  end

  # コレクションをDBに保存するメソッド
  def save
    is_success = true
    ActiveRecord::Base.transaction do
      collection.each do |result|
        # バリデーションを全てかけたいからsave!ではなくsaveを使用
        is_success = false unless result.save
      end
      # バリデーションエラーがあった時は例外を発生させてロールバックさせる
      raise ActiveRecord::RecordInvalid unless is_success
    end
  rescue StandardError
    p 'エラー'
  ensure
    return is_success
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :birthday
    validates :last_name, :first_name
    validates :last_name_kana, :first_name_kana
  end
  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英数字で、6文字以上にしてください' }
  validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: '全角で入力してください' }
  validates :last_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: '全角カタカナで入力してください' }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'はアットマークを含めて入力してください' }

  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'toshi' && password == '1048'
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def index
    @user = User.includes(:user)
    @shift = Shift.includes(:user)
  end


  def create
    @shift = Shift.new(shift_params)
    if @shift.save
      redirect_to new_user_path, notice: "予定を登録しました！"
    else
      render "users/new"
    end
  end

  def update
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      redirect_to new_user_path, notice: "予定を変更しました！" 
    else 
      render "users/edit"
    end
  end

  def show
    @shift = Shift.includes(:user)
    unless user_signed_in? && current_user.admin?
      render :index
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:work_day, :start_time, :end_time, :break_start, :break_end).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.includes(:user)
    @shift = Shift.includes(:user)
  end

  
  def new
    @shift = Shift.new
  end
  
  def destroy
    shift = Shift.find(params[:id])
    if shift.destroy
      redirect_to new_user_path, notice: "予定を取消しました！"     
    else
      render :new
    end
  end
  def edit
    @shift = Shift.find(params[:id])
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>はたらく</h1>
<h2>このアプリはみんなの「はたらく」をサポートします</h2>
　
    <ul class='lists-right'>
      <% if user_signed_in? %>
       <li><%= link_to current_user.last_name, user_path(@user.ids), class: "user-nickname" %></li> 
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
       <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
       <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HataLuck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="reset.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%# <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="js/bootstrap.min.js"></script> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shifts/index.html.erb
<header>
<h1 class="title">はたらっく</h1>
<h4 class="intro">〜 このアプリでかんたんに予定を管理しよう 〜</h4>

</header>
    <ul class='lists-right'>
      <% if user_signed_in? && current_user.admin? %>
       <li><%= link_to '予定確認', shift_path(@shift), class: "btn" %></li>
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %></li>
      <% elsif user_signed_in? %>
       <li><%= link_to current_user.last_name+'さんのページ', new_user_path(current_user.id), class: "btn" %></li> 
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %></li>
      <% else %>
       <li><%= link_to 'ログイン', user_session_path, class: "btn" %></li>
       <li><%= link_to '新規登録', new_user_registration_path, class: "btn" %></li>
      <% end %>
      
    </ul>
    

app/views/shifts/new.html.erb
<h1><%= current_user.last_name %>さんの</h1>
 <h2><%= Time.now.since(2.weeks).monday.strftime('%m/%d') %>(月)から一週間の予定を教えて下さい。</h2>
 <h3>(締切は<%= Time.now.next_week.monday.-(1.day).strftime('%m/%d') %>(日)です。)</h3>

<%= form_with model: @shift, url: shifts_path(current_user.id), class:'shift-main', local: true do |f| %>
    <%= render 'layouts/error_messages', model: @shift %> 
    <ul>
     <li>
      <div class='form-text-wrap'>
       <label class="form-text">日付</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.date_select :work_day, date_separator: "月", use_month_numbers: true, discard_year: true, default: Time.now.since(2.weeks).monday, class:"input-default", id:"work_day" %>日
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label class="form-text">出勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :start_time, ignore_date: true, include_blank: "--", start_hour: 9, end_hour: 22, minute_step: 15, class:"input-default", id:"start_time" %>から
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label class="form-text">退勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :end_time, ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 24, minute_step: 15, class:"input-default", id:"end_time" %>まで
      </div>
     </li>
      <li>
        <div class='form-text-wrap'>
          <label class="form-text">休憩開始</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_start, ignore_date: true, include_blank: "--", start_hour: 10, end_hour: 21, minute_step: 15, class:"input-default", id:"break_start" %>
        </div>
      </li>
      <li>
        <div class='form-text-wrap'>
          <label class="form-text">休憩終了</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_end,ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 22, minute_step: 15, class:"input-default", id:"break_end" %>
        </div>
      </li>
    </ul> 
    <div class='register-btn'>
      <%= f.submit "予定提出", class:"register-red-btn" %>
    </div>
<% end %>

<h3>提出済みの予定はこちらです。</h3>
<% @shift = Shift.where(user_id: current_user.id) %>
  <% @shift.each do |shift| %>
    <li>
        <%= shift.work_day.strftime('%m/%d') %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>  

app/views/shifts/show.html.erb
<header>
  <h1>予定の確認</h1>
</header>

    <% next_mon=Time.now.next_week.monday %>
  <h2>
    <%= next_mon.strftime('%m/%d') %>(月)からの一週間 
  </h2>
    <p>
    　<%= link_to 'トップページへ戻る', shifts_path(@shift), class: "btn" %>
    </p>
  <h3>
    <%= next_mon.strftime('%m/%d') %>(月)
  </h3>
 <% @shift_mon=@shift.where(work_day:next_mon) %>
  <% @shift_mon.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>  
<h3>
  <% next_tue=next_mon.+(1.day) %>
  <%= next_tue.strftime('%m/%d') %>(火)
</h3>
  <% @shift_tue=@shift.where(work_day:next_tue) %>
    <% @shift_tue.each do |shift| %>
      <li>
          <%= shift.user.last_name %>
          <%= shift.user.first_name %>
          <%= shift.start_time.strftime('%H:%M') %>〜
          <%= shift.end_time.strftime('%H:%M') %>
        <% if shift&.break_start.present? %>
          休憩<%= shift.break_start.strftime('%H:%M') %>〜
          <%= shift.break_end.strftime('%H:%M') %>
        <% end %>
      </li>
    <% end %>
<h3>
  <% next_wed=next_mon.+(2.days) %>
  <%= next_wed.strftime('%m/%d') %>(水)
</h3>
 <% @shift_wed=@shift.where(work_day:next_wed) %>
  <% @shift_wed.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next_thu=next_mon.+(3.days) %>
  <%= next_thu.strftime('%m/%d') %>(木)
</h3>
 <% @shift_thu=@shift.where(work_day:next_thu) %>
  <% @shift_thu.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next_fri=next_mon.+(4.days) %>
  <%= next_fri.strftime('%m/%d') %>(金)
</h3>
 <% @shift_fri=@shift.where(work_day:next_fri) %>
  <% @shift_fri.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next_sat=next_mon.+(5.days) %>
  <%= next_sat.strftime('%m/%d') %>(土)
</h3>
 <% @shift_sat=@shift.where(work_day:next_sat) %>
  <% @shift_sat.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next_sun=next_mon.+(6.days) %>
  <%= next_sun.strftime('%m/%d') %>(日)
</h3>
 <% @shift_sun=@shift.where(work_day:next_sun) %>
  <% @shift_sun.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<% next2_mon=Time.now.since(2.weeks).monday %>
<h2><%= next2_mon.strftime('%m/%d') %>(月)からの一週間</h2>
<h3>
  <%= next2_mon.strftime('%m/%d') %>(月)
</h3>
 <% @shift_2mon=@shift.where(work_day:next2_mon) %>
  <% @shift_2mon.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
  
<h3>
  <% next2_tue=next2_mon.+(1.day) %>
  <%= next2_tue.strftime('%m/%d') %>(火)
</h3>
  <% @shift_2tue=@shift.where(work_day:next2_tue) %>
    <% @shift_2tue.each do |shift| %>
      <li>
          <%= shift.user.last_name %>
          <%= shift.user.first_name %>
          <%= shift.start_time.strftime('%H:%M') %>〜
          <%= shift.end_time.strftime('%H:%M') %>
        <% if shift&.break_start.present? %>
          休憩<%= shift.break_start.strftime('%H:%M') %>〜
          <%= shift.break_end.strftime('%H:%M') %>
        <% end %>
      </li>
    <% end %>
<h3>
  <% next2_wed=next2_mon.+(2.days) %>
  <%= next2_wed.strftime('%m/%d') %>(水)
</h3>
 <% @shift_2wed=@shift.where(work_day:next2_wed) %>
  <% @shift_2wed.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next2_thu=next2_mon.+(3.days) %>
  <%= next2_thu.strftime('%m/%d') %>(木)
</h3>
 <% @shift_2thu=@shift.where(work_day:next2_thu) %>
  <% @shift_2thu.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next2_fri=next2_mon.+(4.days) %>
  <%= next2_fri.strftime('%m/%d') %>(金)
</h3>
 <% @shift_2fri=@shift.where(work_day:next2_fri) %>
  <% @shift_2fri.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next2_sat=next2_mon.+(5.days) %>
  <%= next2_sat.strftime('%m/%d') %>(土)
</h3>
 <% @shift_2sat=@shift.where(work_day:next2_sat) %>
  <% @shift_2sat.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>
<h3>
  <% next2_sun=next2_mon.+(6.days) %>
  <%= next2_sun.strftime('%m/%d') %>(日)
</h3>
 <% @shift_2sun=@shift.where(work_day:next2_sun) %>
  <% @shift_2sun.each do |shift| %>
    <li>
        <%= shift.user.last_name %>
        <%= shift.user.first_name %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %>
    </li>
  <% end %>

app/views/users/edit.html.erb
<header>
  <h2>この日の予定を変更しますか？</h2>
</header>
    <ul>
      <li><%= link_to 'マイページへ', new_user_path(@shift), class: "btn" %></li>
      <li><%= link_to 'トップページへ', shifts_path(@shift), class: "btn" %></li>
    </ul>

<%= form_with model: @shift, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @shift %> 
    <ul class="select">
     <li>
      <div class='form-text-wrap'>
       <label>日付</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="date">
       <%= f.date_select :work_day, date_separator: "月", use_month_numbers: true, discard_year: true, default: Time.now.since(2.weeks).monday, class:"input-default", id:"work_day" %>日
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label>出勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :start_time, ignore_date: true, include_blank: "--", start_hour: 9, end_hour: 22, minute_step: 15, class:"input-default", id:"start_time" %>
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label>退勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :end_time, ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 24, minute_step: 15, class:"input-default", id:"end_time" %>
      </div>
     </li>
      <li>
        <div class='form-text-wrap'>
          <label>休憩開始</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_start, ignore_date: true, include_blank: "--", start_hour: 10, end_hour: 21, minute_step: 15, class:"input-default", id:"break_start" %>
        </div>
      </li>
      <li>
        <div class='form-text-wrap'>
          <label>休憩終了</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_end,ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 22, minute_step: 15, class:"input-default", id:"break_end" %>
        </div>
      </li>
    </ul> 
    <li class="edit-btn">
      <%= f.submit "予定変更", class:"edit-red-btn" %>
    </li>
 <% end %>

app/views/users/new.html.erb
<header>
<h1><%= current_user.last_name %>さんの</h1>
 <h2><%= Time.now.since(2.weeks).monday.strftime('%m/%d') %>(月)から一週間の予定を教えて下さい。</h2>
 <h3>(締切は<%= Time.now.next_week.monday.-(1.day).strftime('%m/%d') %>(日)です。)</h3>
</header>
 <%= form_with model: @shift, url: shifts_path(current_user.id), local: true do |f| %>
    <div class="error-messages"><%= render 'layouts/error_messages', model: @shift %></div>
    <ul class="select">
     <li>
      <div class='form-text-wrap'>
       <label class="datelable">日付</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="date">
       <%= f.date_select :work_day, date_separator: "月", use_month_numbers: true, discard_year: true, default: Time.now.since(2.weeks).monday, class:"input-default", id:"work_day" %>日
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label>出勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :start_time, ignore_date: true, include_blank: "--", start_hour: 9, end_hour: 22, minute_step: 15, class:"input-default", id:"start_time" %>
      </div>
     </li>
     <li>
      <div class='form-text-wrap'>
       <label>退勤時間</label>
       <span class="indispensable">(必須)</span>
      </div>
      <div class="datetime">
       <%= f.time_select :end_time, ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 24, minute_step: 15, class:"input-default", id:"end_time" %>
      </div>
     </li>
      <li>
        <div class='form-text-wrap'>
          <label>休憩開始</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_start, ignore_date: true, include_blank: "--", start_hour: 10, end_hour: 21, minute_step: 15, class:"input-default", id:"break_start" %>
        </div>
      </li>
      <li>
        <div class='form-text-wrap'>
          <label>休憩終了</label>
          <span class="indispensable">(任意)</span>
        </div>
        <div class="datetime">
          <%= f.time_select :break_end,ignore_date: true, include_blank: "--", start_hour: 11, end_hour: 22, minute_step: 15, class:"input-default", id:"break_end" %>
        </div>
      </li>
    </ul> 
    <li class="new-btn">
      <%= f.submit "予定提出", class:"new-red-btn" %>
    </li>
 <% end %>
  <div class='login-flash-message'>
    <%= flash[:notice] %>
  </div>
<h3 class="new-btn">提出済みの予定はこちらです。</h3>
 <% @shift = Shift.where(user_id: current_user.id) %>
  <% @shift.each do |shift| %>
    <li class="new-btn" >
     <% if shift.work_day > Time.now %>
        <%= shift.work_day.strftime('%m/%d') %>
        <%= shift.start_time.strftime('%H:%M') %>〜
        <%= shift.end_time.strftime('%H:%M') %>
      <% if shift&.break_start.present? %>
        休憩<%= shift.break_start.strftime('%H:%M') %>〜
        <%= shift.break_end.strftime('%H:%M') %>
      <% end %> 
     <% end %>

      <% if shift.work_day > Time.now.since(2.weeks).monday.-(1.day) %>
        <%= link_to '変更', edit_user_path(shift.id), method: :get, class:"new-red-btn" %>
        <%= link_to '取消', user_path(shift.id), method: :delete, class:"new-red-btn" %>
      <% end %>
    </li>
  <% end %>  
 <li class="new-btn"><%= link_to 'トップページへ', shifts_path(@shift), class: "btn" %></li>
 